### ISSUE TITLE
Is there `scripts/plan_guided.py` ?

### ISSUE THREAD

**Issue by somisawa** [jannerm/diffuser#1]
In Usage section of README, it is demonstrated that
```bash
python scripts/plan_guided.py --dataset hopper-medium-replay-v2 \
    --horizon 512 --n_diffusion_steps 200
```
but it seems that there are no file corresponding to the `scripts/plan_guided.py` .

**Comment by jannerm** [comment]
That should read `python scripts/train.py`. I've fixed it in [this commit](https://github.com/jannerm/diffuser/commit/77c687024b740e5ecaf99622eefabb3266fe9b4e). Thanks for the heads-up!
