### ISSUE TITLE
Couldn't reproduce with Docker

### ISSUE THREAD

**Issue by kevmo314** [jannerm/diffuser#11]
I ran the training steps with Docker

```
docker build -f azure/Dockerfile . -t diffuser
docker run -it --rm --gpus all \
    --mount type=bind,source=$PWD,target=/home/code \
    --mount type=bind,source=$HOME/.d4rl,target=/root/.d4rl \
    diffuser \
    bash -c \
    "export PYTHONPATH=$PYTHONPATH:/home/code && \
    python /home/code/scripts/train.py --dataset hopper-medium-expert-v2 --logbase logs/docker"
```

However after 200k+ iterations it did not appear to increase the episode length. Could you provide more details on how you trained your agent and how I can reproduce it?

**Comment by jannerm** [comment]
The guided sampling code has now been released; see [this section of the README](https://github.com/jannerm/diffuser#using-pretrained-models) for instructions on how to run it. Let us know if you run into any issues!
