### ISSUE TITLE
GCC Error

### ISSUE THREAD

**Issue by Charlie0257** [jannerm/diffuser#15]
When I try the following command——
`python scripts/train.py --dataset halfcheetah-medium-expert-v2`

There is an error occurring——
`gcc: error: unrecognized command line option ‘-R’`
`Traceback (most recent call last):`
 ` File "/home/charlie/.local/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py", line 204, in link`
   ` self.spawn(linker + ld_args)`
 ` File "/home/charlie/.local/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 910, in spawn`
   ` spawn(cmd, dry_run=self.dry_run, **kwargs)`
  `File "/home/charlie/.local/lib/python3.8/site-packages/setuptools/_distutils/spawn.py", line 87, in spawn`
    `raise DistutilsExecError(`
`distutils.errors.DistutilsExecError: command '/usr/bin/gcc' failed with exit code 1`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):`
  `File "scripts/train.py", line 1, in <module>`
    `import diffuser.utils as utils`
  `File "/home/charlie/PycharmProjects/diffuser/diffuser/utils/__init__.py", line 6, in <module>`
    `from .rendering import *`
  `File "/home/charlie/PycharmProjects/diffuser/diffuser/utils/rendering.py", line 8, in <module>`
    `import mujoco_py as mjc`
  `File "/home/charlie/anaconda3/envs/diffuser/lib/python3.8/site-packages/mujoco_py/__init__.py", line 3, in <module>`
    `from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException`
  `File "/home/charlie/anaconda3/envs/diffuser/lib/python3.8/site-packages/mujoco_py/builder.py", line 510, in <module>`
    `cymj = load_cython_ext(mujoco_path)`
  `File "/home/charlie/anaconda3/envs/diffuser/lib/python3.8/site-packages/mujoco_py/builder.py", line 105, in load_cython_ext`
    `cext_so_path = builder.build()`
  `File "/home/charlie/anaconda3/envs/diffuser/lib/python3.8/site-packages/mujoco_py/builder.py", line 221, in build`
    `built_so_file_path = self._build_impl()`
  `File "/home/charlie/anaconda3/envs/diffuser/lib/python3.8/site-packages/mujoco_py/builder.py", line 291, in _build_impl`
    `so_file_path = super()._build_impl()`
  `File "/home/charlie/anaconda3/envs/diffuser/lib/python3.8/site-packages/mujoco_py/builder.py", line 244, in _build_impl`
    `dist.run_commands()`
  `File "/home/charlie/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands`
    `self.run_command(cmd)`
  `File "/home/charlie/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command`
    `cmd_obj.run()`
  `File "/home/charlie/anaconda3/envs/diffuser/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run`
    `_build_ext.build_ext.run(self)`
  `File "/home/charlie/.local/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 341, in run`
    `self.build_extensions()`
 `File "/home/charlie/anaconda3/envs/diffuser/lib/python3.8/site-packages/mujoco_py/builder.py", line 144, in build_extensions`
    `build_ext.build_extensions(self)`
  `File "/home/charlie/anaconda3/envs/diffuser/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions`
    `_build_ext.build_ext.build_extensions(self)`
  `File "/home/charlie/.local/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 450, in build_extensions`
    `self._build_extensions_serial()`
  `File "/home/charlie/.local/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 475, in _build_extensions_serial`
    `self.build_extension(ext)`
  `File "/home/charlie/.local/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 552, in build_extension`
    `self.compiler.link_shared_object(`
  `File "/home/charlie/.local/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 713, in link_shared_object`
    `self.link(CCompiler.SHARED_OBJECT, objects,`
  `File "/home/charlie/.local/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py", line 206, in link`
    `raise LinkError(msg)`
`distutils.errors.LinkError: command '/usr/bin/gcc' failed with exit code 1`

This seems to be an error about GCC.
Could you tell me the versions of gcc and g++ you used or Do you have other better solutions?

Thanks for any help!

**Comment by jannerm** [comment]
Yeah, this looks like a gcc error caused by compilation of mujoco_py. My gcc version is 9.4.0. Though instead of updating gcc on your local machine, I would recommend using the [Dockerfile](https://github.com/jannerm/diffuser#docker) or [Singularity definition file](https://github.com/jannerm/diffuser#singularity) to ensure version compatibility.

**Comment by Charlie0257** [comment]
@jannerm Thanks for your suggestion :)
Actually, the error can be solved by https://github.com/rbgirshick/py-faster-rcnn/issues/706.
