### ISSUE TITLE
Missing Kuka robot envs?

### ISSUE THREAD

**Issue by joeybose** [jannerm/diffuser#17]
Hi,

Thanks for sharing your code and the implementation details. I was trying to reproduce the stacking experiments but I wasn't able to find the exact training scripts or code for this. I'm terribly sorry if I missed this in the repo. Would it be possible to release this env/code for these experiments. Many thanks in advance.

**Comment by yilundu** [comment]
Hi,

You can see the code in the kuka branch of the repo.

**Comment by joeybose** [comment]
Ah great. Thanks for pointing out. Closing this issue now.
