### ISSUE TITLE
Question about the input of training values?

### ISSUE THREAD

**Issue by davidkillerhahaha** [jannerm/diffuser#18]
Hello,
Thanks for the open sourcing codes!
But I have one question about the implementation of training values. Should the input of this line be x_start instead of x_noisy? Because the target is accumulated return calculated from the expert trajectory of offline data and not the true return of denoising trajectories during the denoising or noisy trajecotories, which means the gradient guide from target is not matching to x_noisy. I don't know whether I am right about this, please take a look and offer me some hints. 
https://github.com/jannerm/diffuser/blob/cbcd3fb6f2a95538de19604f0621903bb160d0a1/diffuser/models/diffusion.py#L243

**Comment by jannerm** [comment]
The value guide predicts the return of a trajectory `T=(s_0 a_0 s_1 a_1 ... s_H a_H)` from noisy versions of `T`. The trajectory `T` need not come from an expert.

**Comment by wen1tao1** [comment]
> The value guide predicts the return of a trajectory `T=(s_0 a_0 s_1 a_1 ... s_H a_H)` from noisy versions of `T`. The trajectory `T` need not come from an expert.

What is  trajectory T=(s_0 a_0 s_1 a_1 ... s_H a_H)？
