### ISSUE TITLE
Are Paper Reviews Available?

### ISSUE THREAD

**Issue by kkaytekin** [jannerm/diffuser#19]
Hi there,
Are the paper reviews also available for open access? I could not find it on [openreview.net](www.openreview.net)
Best,
Kagan

**Comment by jannerm** [comment]
I have uploaded the paper reviews [here](https://github.com/diffusion-planning/diffusion-planning.github.io/blob/master/misc/reviews.pdf). (They weren't on OpenReview because ICML 2022 reviewing happened on CMT.)
