### ISSUE TITLE
"conda env create -f environment.yml" not works

### ISSUE THREAD

**Issue by YIN95** [jannerm/diffuser#2]
Hi, 

I directly clone the repo, then the first step is 'conda env create -f environment.yml'. 
However, it stuck at installing pip packages.

**Comment by xmlyqing00** [comment]
I got the same error. Tried on Ubuntu and WSL on Windows.

```
  Cloning git://github.com/deepmind/dm_control (to revision 90f00e4e80af56abb9f905070d0c152845db5602) to /tmp/pip-install-3vcu302m/dm-control_37a45e8a430d481bbfb08d9228e4162c

Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/JannerM/d4rl.git /tmp/pip-req-build-0uop8m7g
  Running command git rev-parse -q --verify 'sha^d5719e2c6ef6ab3b1c678a846c02621abb8074a4'
  Running command git fetch -q https://github.com/JannerM/d4rl.git d5719e2c6ef6ab3b1c678a846c02621abb8074a4
  Running command git checkout -q d5719e2c6ef6ab3b1c678a846c02621abb8074a4
warning: missing-index-doctype

× The package index page being used does not have a proper HTML doctype declaration.
╰─> Problematic URL: https://download.pytorch.org/whl/torch_stable.html

note: This is an issue with the page at the URL mentioned above.
hint: You might need to reach out to the owner of that package index, to get this fixed. See https://github.com/pypa/pip/issues/10825 for context.
  WARNING: Missing build requirements in pyproject.toml for mujoco-py==2.0.2.13 from https://files.pythonhosted.org/packages/2f/48/b108057c1a23c8da9f4cdc7a7c46ab7cec49c3563c0706d50f2527de6ba0/mujoco-py-2.0.2.13.tar.gz#sha256=d6ae66276b565af9063597fda70683a89c7356290f5ac3961b794ee90ec50eea (from -r /Ship03/Sources/diffuser/condaenv.vybgy39v.requirements.txt (line 4)).
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
  Running command git clone --filter=blob:none --quiet git://github.com/deepmind/dm_control /tmp/pip-install-3vcu302m/dm-control_37a45e8a430d481bbfb08d9228e4162c
  fatal: unable to connect to github.com:
  github.com[0: 140.82.112.4]: errno=Connection timed out

  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet git://github.com/deepmind/dm_control /tmp/pip-install-3vcu302m/dm-control_37a45e8a430d481bbfb08d9228e4162c did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet git://github.com/deepmind/dm_control /tmp/pip-install-3vcu302m/dm-control_37a45e8a430d481bbfb08d9228e4162c did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: You are using pip version 22.0.3; however, version 22.1.1 is available.
You should consider upgrading via the '/home/yq/miniconda3/envs/diffuser/bin/python -m pip install --upgrade pip' command.

failed

CondaEnvException: Pip failed
```

**Comment by jannerm** [comment]
Thanks for flagging this. I haven't yet been able to reproduce this on my machines, so there might be some difference in setup that is causing this. While I investigate further, could you post the content of your `~/.gitconfig`? (Feel free to redact any personal information.)

**Comment by jannerm** [comment]
Does https://github.com/jannerm/diffuser/commit/067bd52d603b29687c11eabc088ec87c45b3e6f0 fix the issue?

**Comment by xmlyqing00** [comment]
I follow the docker solution to do it. It works well in the docker.

**Comment by YIN95** [comment]
> Thanks for flagging this. I haven't yet been able to reproduce this on my machines, so there might be some difference in setup that is causing this. While I investigate further, could you post the content of your `~/.gitconfig`? (Feel free to redact any personal information.)

cat ~/.gitconfig
[user]
        email = my email
        name = my name

**Comment by jannerm** [comment]
Thanks @YIN95. Does the issue persist after https://github.com/jannerm/diffuser/commit/067bd52d603b29687c11eabc088ec87c45b3e6f0?

**Comment by YIN95** [comment]
> Thanks @YIN95. Does the issue persist after [067bd52](https://github.com/jannerm/diffuser/commit/067bd52d603b29687c11eabc088ec87c45b3e6f0)?

conda env create -f environment.yml
Collecting package metadata (repodata.jsondone
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 4.13.0

Please update conda by running

    $ conda update -n base -c defaults conda


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip - Ran pip subprocess with arguments:
['/home/ywj/miniconda3/envs/diffuser/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/ywj/Desktop/Code/diffuser/condaenv.31997sjn.requirements.txt']
Pip subprocess output:
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting git+https://github.com/JannerM/d4rl.git@13fc08c198d17ac627f528aedc70843e8f86bb71 (from -r /home/ywj/Desktop/Code/diffuser/condaenv.31997sjn.requirements.txt (line 8))
  Cloning https://github.com/JannerM/d4rl.git (to revision 13fc08c198d17ac627f528aedc70843e8f86bb71) to /tmp/pip-req-build-wtbwrxzk
  Resolved https://github.com/JannerM/d4rl.git to commit 13fc08c198d17ac627f528aedc70843e8f86bb71
Collecting numpy
  Using cached numpy-1.22.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.9 MB)
Collecting gym==0.18.0
  Using cached gym-0.18.0-py3-none-any.whl
Collecting mujoco-py==2.0.2.13
  Using cached mujoco-py-2.0.2.13.tar.gz (792 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting matplotlib==3.3.4
  Using cached matplotlib-3.3.4-cp38-cp38-manylinux1_x86_64.whl (11.6 MB)
Collecting torch==1.9.1+cu111
  Using cached https://download.pytorch.org/whl/cu111/torch-1.9.1%2Bcu111-cp38-cp38-linux_x86_64.whl (2041.3 MB)
Collecting typed-argument-parser
  Using cached typed_argument_parser-1.7.2-py3-none-any.whl
Collecting scikit-image==0.17.2
  Using cached scikit_image-0.17.2-cp38-cp38-manylinux1_x86_64.whl (12.4 MB)
Collecting scikit-video==1.1.11
  Using cached scikit_video-1.1.11-py2.py3-none-any.whl (2.3 MB)
Collecting gitpython
  Using cached GitPython-3.1.27-py3-none-any.whl (181 kB)
Collecting einops
  Using cached einops-0.4.1-py3-none-any.whl (28 kB)
Collecting pillow
  Using cached Pillow-9.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
Collecting tqdm
  Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
Collecting pandas
  Using cached pandas-1.4.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
Collecting wandb
  Downloading wandb-0.12.17-py2.py3-none-any.whl (1.8 MB)
Collecting flax>=0.3.5
  Using cached flax-0.5.0-py3-none-any.whl (190 kB)
Collecting jax<=0.2.21
  Using cached jax-0.2.21-py3-none-any.whl
Collecting ray==1.9.1
  Using cached ray-1.9.1-cp38-cp38-manylinux2014_x86_64.whl (57.4 MB)
Collecting crcmod
  Using cached crcmod-1.7-cp38-cp38-linux_x86_64.whl
Collecting scipy
  Using cached scipy-1.8.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (41.6 MB)
Collecting cloudpickle<1.7.0,>=1.2.0
  Using cached cloudpickle-1.6.0-py3-none-any.whl (23 kB)
Collecting pyglet<=1.5.0,>=1.4.0
  Using cached pyglet-1.5.0-py2.py3-none-any.whl (1.0 MB)
Collecting pillow
  Using cached Pillow-7.2.0-cp38-cp38-manylinux1_x86_64.whl (2.2 MB)
Collecting Cython>=0.27.2
  Using cached Cython-0.29.30-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
Collecting cffi>=1.10
  Using cached cffi-1.15.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (446 kB)
Collecting fasteners~=0.15
  Using cached fasteners-0.17.3-py3-none-any.whl (18 kB)
Collecting imageio>=2.1.2
  Using cached imageio-2.19.3-py3-none-any.whl (3.4 MB)
Collecting glfw>=1.4.0
  Using cached glfw-2.5.3-py2.py27.py3.py30.py31.py32.py33.py34.py35.py36.py37.py38-none-manylinux2014_x86_64.whl (206 kB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.4.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.2 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Collecting networkx>=2.0
  Using cached networkx-2.8.2-py3-none-any.whl (2.0 MB)
Collecting tifffile>=2019.7.26
  Using cached tifffile-2022.5.4-py3-none-any.whl (195 kB)
Collecting PyWavelets>=1.1.1
  Using cached PyWavelets-1.3.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.9 MB)
Collecting redis>=3.5.0
  Using cached redis-4.3.1-py3-none-any.whl (241 kB)
Collecting grpcio>=1.28.1
  Using cached grpcio-1.46.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.4 MB)
Collecting click>=7.0
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting msgpack<2.0.0,>=1.0.0
  Using cached msgpack-1.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (322 kB)
Collecting pyyaml
  Using cached PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
Collecting attrs
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting protobuf>=3.15.3
  Downloading protobuf-4.21.1-cp37-abi3-manylinux2014_x86_64.whl (407 kB)
Collecting jsonschema
  Using cached jsonschema-4.5.1-py3-none-any.whl (72 kB)
Collecting filelock
  Using cached filelock-3.7.0-py3-none-any.whl (10 kB)
Collecting typing-inspect>=0.7.1
  Using cached typing_inspect-0.7.1-py3-none-any.whl (8.4 kB)
Collecting dm_control@ git+git://github.com/deepmind/dm_control@41d0c7383153f9ca6c12f8e865ef5e73a98759bd#egg=dm_control
  Cloning git://github.com/deepmind/dm_control (to revision 41d0c7383153f9ca6c12f8e865ef5e73a98759bd) to /tmp/pip-install-jxgjvmob/dm-control_43fbb2cedcf341ffb69bb60cd213a71d
Collecting mjrl@ git+git://github.com/aravindr93/mjrl@master#egg=mjrl
  Cloning git://github.com/aravindr93/mjrl (to revision master) to /tmp/pip-install-jxgjvmob/mjrl_3b7daa4bb3c34b8a8683c6c2e97d1134
Collecting pybullet
  Using cached pybullet-3.2.5-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (91.7 MB)
Collecting h5py
  Using cached h5py-3.7.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (4.5 MB)
Collecting termcolor
  Using cached termcolor-1.1.0-py3-none-any.whl
INFO: pip is looking at multiple versions of typed-argument-parser to determine which version is compatible with other requirements. This could take a while.
Collecting typed-argument-parser
  Using cached typed-argument-parser-1.7.1.tar.gz (25 kB)
  Using cached typed-argument-parser-1.7.0.tar.gz (25 kB)
  Using cached typed-argument-parser-1.6.3.tar.gz (25 kB)
Collecting typing-inspect==0.6.0
  Using cached typing_inspect-0.6.0-py3-none-any.whl (8.1 kB)
Collecting mypy-extensions>=0.3.0
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
INFO: pip is looking at multiple versions of typing-inspect to determine which version is compatible with other requirements. This could take a while.
Collecting typed-argument-parser
  Using cached typed-argument-parser-1.6.2.tar.gz (25 kB)
  Using cached typed-argument-parser-1.6.1.tar.gz (24 kB)
  Using cached typed-argument-parser-1.6.0.tar.gz (24 kB)
  Using cached typed-argument-parser-1.5.4.tar.gz (22 kB)
INFO: pip is looking at multiple versions of typed-argument-parser to determine which version is compatible with other requirements. This could take a while.
  Using cached typed-argument-parser-1.5.3.tar.gz (22 kB)
  Using cached typed-argument-parser-1.5.2.tar.gz (22 kB)
  Using cached typed-argument-parser-1.5.1.tar.gz (22 kB)
  Using cached typed-argument-parser-1.5.0.tar.gz (21 kB)
  Using cached typed-argument-parser-1.4.3.tar.gz (21 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached typed-argument-parser-1.4.2.tar.gz (20 kB)
  Using cached typed-argument-parser-1.4.1.tar.gz (18 kB)
  Using cached typed-argument-parser-1.4.tar.gz (16 kB)
  Using cached typed-argument-parser-1.3.tar.gz (14 kB)
  Using cached typed-argument-parser-1.2.tar.gz (14 kB)
INFO: pip is looking at multiple versions of numpy to determine which version is compatible with other requirements. This could take a while.
Collecting numpy
  Using cached numpy-1.22.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
  Using cached numpy-1.22.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
  Using cached numpy-1.22.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
  Using cached numpy-1.22.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
  Using cached numpy-1.21.6-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
  Using cached numpy-1.21.5-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
  Using cached numpy-1.21.4-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
INFO: pip is looking at multiple versions of typing-inspect to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of numpy to determine which version is compatible with other requirements. This could take a while.
  Using cached numpy-1.21.3-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
  Using cached numpy-1.21.2-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.8 MB)
  Using cached numpy-1.21.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.8 MB)
  Using cached numpy-1.21.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
  Using cached numpy-1.20.3-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.4 MB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached numpy-1.20.2-cp38-cp38-manylinux2010_x86_64.whl (15.4 MB)
  Using cached numpy-1.20.1-cp38-cp38-manylinux2010_x86_64.whl (15.4 MB)
  Using cached numpy-1.20.0-cp38-cp38-manylinux2010_x86_64.whl (15.4 MB)
  Using cached numpy-1.19.5-cp38-cp38-manylinux2010_x86_64.whl (14.9 MB)
  Using cached numpy-1.19.4-cp38-cp38-manylinux2010_x86_64.whl (14.5 MB)
  Using cached numpy-1.19.3-cp38-cp38-manylinux2010_x86_64.whl (14.9 MB)
  Using cached numpy-1.19.2-cp38-cp38-manylinux2010_x86_64.whl (14.5 MB)
  Using cached numpy-1.19.1-cp38-cp38-manylinux2010_x86_64.whl (14.5 MB)
  Using cached numpy-1.19.0-cp38-cp38-manylinux2010_x86_64.whl (14.6 MB)
  Using cached numpy-1.18.5-cp38-cp38-manylinux1_x86_64.whl (20.6 MB)
  Using cached numpy-1.18.4-cp38-cp38-manylinux1_x86_64.whl (20.7 MB)
  Using cached numpy-1.18.3-cp38-cp38-manylinux1_x86_64.whl (20.6 MB)
  Using cached numpy-1.18.2-cp38-cp38-manylinux1_x86_64.whl (20.6 MB)
  Using cached numpy-1.18.1-cp38-cp38-manylinux1_x86_64.whl (20.6 MB)
  Using cached numpy-1.18.0-cp38-cp38-manylinux1_x86_64.whl (20.6 MB)
  Using cached numpy-1.17.5-cp38-cp38-manylinux1_x86_64.whl (20.5 MB)
  Using cached numpy-1.17.4-cp38-cp38-manylinux1_x86_64.whl (20.5 MB)
  Using cached numpy-1.17.3-cp38-cp38-manylinux1_x86_64.whl (20.5 MB)
  Using cached numpy-1.17.2.zip (6.5 MB)
  Using cached numpy-1.17.1.zip (6.5 MB)
  Using cached numpy-1.17.0.zip (6.5 MB)
  Using cached numpy-1.16.6.zip (5.1 MB)
  Using cached numpy-1.16.5.zip (5.1 MB)
  Using cached numpy-1.16.4.zip (5.1 MB)
  Using cached numpy-1.16.3.zip (5.1 MB)
  Using cached numpy-1.16.2.zip (5.1 MB)
  Using cached numpy-1.16.1.zip (5.1 MB)
  Using cached numpy-1.16.0.zip (5.1 MB)
INFO: pip is looking at multiple versions of ray to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of scikit-video to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of scikit-image to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of torch to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of matplotlib to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of mujoco-py to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of gym to determine which version is compatible with other requirements. This could take a while.

Pip subprocess error:
  Running command git clone -q https://github.com/JannerM/d4rl.git /tmp/pip-req-build-wtbwrxzk
  Running command git rev-parse -q --verify 'sha^13fc08c198d17ac627f528aedc70843e8f86bb71'
  Running command git fetch -q https://github.com/JannerM/d4rl.git 13fc08c198d17ac627f528aedc70843e8f86bb71
  Running command git checkout -q 13fc08c198d17ac627f528aedc70843e8f86bb71
  WARNING: Missing build requirements in pyproject.toml for mujoco-py==2.0.2.13 from https://files.pythonhosted.org/packages/2f/48/b108057c1a23c8da9f4cdc7a7c46ab7cec49c3563c0706d50f2527de6ba0/mujoco-py-2.0.2.13.tar.gz#sha256=d6ae66276b565af9063597fda70683a89c7356290f5ac3961b794ee90ec50eea (from -r /home/ywj/Desktop/Code/diffuser/condaenv.31997sjn.requirements.txt (line 4)).
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
  Running command git clone -q git://github.com/deepmind/dm_control /tmp/pip-install-jxgjvmob/dm-control_43fbb2cedcf341ffb69bb60cd213a71d
  fatal: unable to connect to github.com:
  github.com[0: 140.82.121.3]: errno=Connection timed out

WARNING: Discarding git+git://github.com/deepmind/dm_control@41d0c7383153f9ca6c12f8e865ef5e73a98759bd#egg=dm_control. Command errored out with exit status 128: git clone -q git://github.com/deepmind/dm_control /tmp/pip-install-jxgjvmob/dm-control_43fbb2cedcf341ffb69bb60cd213a71d Check the logs for full command output.
  Running command git clone -q git://github.com/aravindr93/mjrl /tmp/pip-install-jxgjvmob/mjrl_3b7daa4bb3c34b8a8683c6c2e97d1134
  fatal: unable to connect to github.com:
  github.com[0: 140.82.121.3]: errno=Connection timed out

WARNING: Discarding git+git://github.com/aravindr93/mjrl@master#egg=mjrl. Command errored out with exit status 128: git clone -q git://github.com/aravindr93/mjrl /tmp/pip-install-jxgjvmob/mjrl_3b7daa4bb3c34b8a8683c6c2e97d1134 Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement dm-control (unavailable) (from d4rl) (from versions: 0.0.286587932, 0.0.286955599, 0.0.288398964, 0.0.288483845, 0.0.295778102, 0.0.300771433, 0.0.312466143, 0.0.318037100, 0.0.318066097, 0.0.319497192, 0.0.322773188, 0.0.355168290, 0.0.364896371, 0.0.403778684, 0.0.423341706, 0.0.425341097, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.3.post1)
ERROR: No matching distribution found for dm-control (unavailable)

failed

CondaEnvException: Pip failed

**Comment by jannerm** [comment]
This is a bit of a long shot, but what happens if you add:
```
[url "https://"]
        insteadOf = git://
```
to your `~/.gitconfig`?

If that doesn't work, could you try installing `mjrl` separately from the other dependencies?
```
pip install git+git://github.com/aravindr93/mjrl
```

**Comment by AIasd** [comment]
Adding
```
[url "https://"]
        insteadOf = git://
``` 
to `~/.gitconfig` leads to the following error:
```
...
Successfully built gym typed-argument-parser d4rl jax crcmod dm-control future mjrl
Failed to build mujoco-py

Pip subprocess error:
  Running command git clone -q https://github.com/JannerM/d4rl.git /tmp/pip-req-build-5b4848nw
  Running command git rev-parse -q --verify 'sha^13fc08c198d17ac627f528aedc70843e8f86bb71'
  Running command git fetch -q https://github.com/JannerM/d4rl.git 13fc08c198d17ac627f528aedc70843e8f86bb71
  Running command git checkout -q 13fc08c198d17ac627f528aedc70843e8f86bb71
  WARNING: Missing build requirements in pyproject.toml for mujoco-py==2.0.2.13 from https://files.pythonhosted.org/packages/2f/48/b108057c1a23c8da9f4cdc7a7c46ab7cec49c3563c0706d50f2527de6ba0/mujoco-py-2.0.2.13.tar.gz#sha256=d6ae66276b565af9063597fda70683a89c7356290f5ac3961b794ee90ec50eea (from -r /home/zhongzzy9/Documents/self-driving-cars/summer_project/diffuser/condaenv.1dw9kknl.requirements.txt (line 4)).
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
  Running command git clone -q git://github.com/deepmind/dm_control /tmp/pip-install-cglfpm2r/dm-control_c291c504c4e34cb98bc98cbffe139744
  Running command git rev-parse -q --verify 'sha^41d0c7383153f9ca6c12f8e865ef5e73a98759bd'
  Running command git fetch -q git://github.com/deepmind/dm_control 41d0c7383153f9ca6c12f8e865ef5e73a98759bd
  Running command git clone -q git://github.com/aravindr93/mjrl /tmp/pip-install-cglfpm2r/mjrl_6103e5746a5343c08f7530cc21bd8893
  ERROR: Command errored out with exit status 1:
   command: /home/zhongzzy9/anaconda3/envs/diffuser/bin/python /home/zhongzzy9/anaconda3/envs/diffuser/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp7l45wyf6
       cwd: /tmp/pip-install-cglfpm2r/mujoco-py_2202caa7cb0c47b192def1fca87a06e7
  Complete output (73 lines):
  running bdist_wheel
  running build
  
  You appear to be missing MuJoCo.  We expected to find the file here: /home/zhongzzy9/.mujoco/mujoco200
  
  This package only provides python bindings, the library must be installed separately.
  
  Please follow the instructions on the README to install MuJoCo
  
      https://github.com/openai/mujoco-py#install-mujoco
  
  Which can be downloaded from the website
  
      https://www.roboti.us/index.html
  
  Traceback (most recent call last):
    File "/home/zhongzzy9/anaconda3/envs/diffuser/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/zhongzzy9/anaconda3/envs/diffuser/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/zhongzzy9/anaconda3/envs/diffuser/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 248, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-fcf8cpqg/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 244, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-fcf8cpqg/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-fcf8cpqg/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 281, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-fcf8cpqg/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 33, in <module>
      setup(
    File "/tmp/pip-build-env-fcf8cpqg/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-fcf8cpqg/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-fcf8cpqg/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-fcf8cpqg/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-fcf8cpqg/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1229, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-fcf8cpqg/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-fcf8cpqg/normal/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/tmp/pip-build-env-fcf8cpqg/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-fcf8cpqg/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1229, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-fcf8cpqg/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "setup.py", line 29, in run
      import mujoco_py  # noqa: force build
    File "/tmp/pip-install-cglfpm2r/mujoco-py_2202caa7cb0c47b192def1fca87a06e7/mujoco_py/__init__.py", line 3, in <module>
      from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
    File "/tmp/pip-install-cglfpm2r/mujoco-py_2202caa7cb0c47b192def1fca87a06e7/mujoco_py/builder.py", line 509, in <module>
      mujoco_path, key_path = discover_mujoco()
    File "/tmp/pip-install-cglfpm2r/mujoco-py_2202caa7cb0c47b192def1fca87a06e7/mujoco_py/utils.py", line 93, in discover_mujoco
      raise Exception(message)
  Exception:
  You appear to be missing MuJoCo.  We expected to find the file here: /home/zhongzzy9/.mujoco/mujoco200
  
  This package only provides python bindings, the library must be installed separately.
  
  Please follow the instructions on the README to install MuJoCo
  
      https://github.com/openai/mujoco-py#install-mujoco
  
  Which can be downloaded from the website
  
      https://www.roboti.us/index.html
  
  ----------------------------------------
  ERROR: Failed building wheel for mujoco-py
ERROR: Could not build wheels for mujoco-py which use PEP 517 and cannot be installed directly

failed

CondaEnvException: Pip failed
```

**Comment by jannerm** [comment]
This appears to be a MuJoCo installation problem instead of a git problem. Is MuJoCo installed at `~/.mujoco/mujoco200`?

**Comment by jannerm** [comment]
We have updated the `environment.yml` file to point to a [more recent version of D4RL](https://github.com/jannerm/diffuser/blob/9af0d8a02f400bb1798b99d413b1ff98ea4f0a84/environment.yml#L17). This should hopefully avoid versioning issues.

**Comment by shaantanu314** [comment]
@jannerm  Please do it for kuka branch as well. Same issue happens there as well
