### ISSUE TITLE
About network architectures

### ISSUE THREAD

**Issue by dolts4444** [jannerm/diffuser#21]
Hi,
Have you tried other network architecture other than UNet such as MLP or TCN. Is network architecture important for performance.

**Comment by jannerm** [comment]
We didn't tune extensively over the network architecture -- if you do, we would be interested in hearing how it goes! U-Nets have become fairly standard for diffusion models, so they were a natural place to start.

**Comment by qianlin04** [comment]
Thanks for your reply. U-Nets seems to violate the Markov property where the following states and actions can influence the previous ones. I try vanilla temporal casual convolutional network which causes the performance damage. Maybe the bottleneck or concatenation with cropped features is important for long horizon sequence generation. 

By the way, can you try any other planning horizon in mujoco env, such as 64, 128.  And what‘s the impact of the inconsistency between trainning horizon and planning horizon, such as trainning with 32 and planning with 64?

**Comment by jannerm** [comment]
The non-Markovian nature of the model is probably important for the performance. Even though you would not need it for prediction in an MDP, planning requires taking into account the future, and Diffuser is doing both prediction and planning simultaneously. (See the paragraph labeled **Temporal ordering** in §3.1 for more details.)

From memory, I did not notice much of an effect from changing the prediction horizon.

**Comment by qianlin04** [comment]
Oh, your reply hit me a lot. I almost forget this important idea of diffuser. Thanks.
