### ISSUE TITLE
Error in creating conda environment for plan_maze2d branch

### ISSUE THREAD

**Issue by RobotLearner2022** [jannerm/diffuser#22]
Hi there, I checked out the plan_maze2d branch and tried to run "conda env create -f environment.yml" and bump into the following errors. Any guidance on how to solve this issue? Thank you very much!

Collecting dm_control@ git+git://github.com/deepmind/dm_control@41d0c7383153f9ca6c12f8e865ef5e73a98759bd#egg=dm_control
  Cloning git://github.com/deepmind/dm_control (to revision 41d0c7383153f9ca6c12f8e865ef5e73a98759bd) to /tmp/pip-install-ncjf6ze3/dm-control_fcf322da5da84fb9a7196336199dff53

Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/JannerM/d4rl.git /tmp/pip-req-build-tmbo87ge
  Running command git rev-parse -q --verify 'sha^13fc08c198d17ac627f528aedc70843e8f86bb71'
  Running command git fetch -q https://github.com/JannerM/d4rl.git 13fc08c198d17ac627f528aedc70843e8f86bb71
  Running command git checkout -q 13fc08c198d17ac627f528aedc70843e8f86bb71
  WARNING: Missing build requirements in pyproject.toml for mujoco-py==2.0.2.13 from https://files.pythonhosted.org/packages/2f/48/b108057c1a23c8da9f4cdc7a7c46ab7cec49c3563c0706d50f2527de6ba0/mujoco-py-2.0.2.13.tar.gz (from -r /home/external/diffuser/condaenv.75wnjbo_.requirements.txt (line 4)).
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
  Running command git clone --filter=blob:none --quiet git://github.com/deepmind/dm_control /tmp/pip-install-ncjf6ze3/dm-control_fcf322da5da84fb9a7196336199dff53
  fatal: unable to connect to github.com:
  github.com[0: 192.30.255.113]: errno=Connection timed out

  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet git://github.com/deepmind/dm_control /tmp/pip-install-ncjf6ze3/dm-control_fcf322da5da84fb9a7196336199dff53 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet git://github.com/deepmind/dm_control /tmp/pip-install-ncjf6ze3/dm-control_fcf322da5da84fb9a7196336199dff53 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

failed

CondaEnvException: Pip failed

**Comment by jannerm** [comment]
I updated the `maze2d` environment config file to match that from the `main` branch in [this commit](https://github.com/jannerm/diffuser/commit/13b4d404bdbd9d0d74c08d5a51ee39f84e765830). Let me know if you have further issues.

**Comment by RobotLearner2022** [comment]
Thank you so much for updating the env config file. I pulled the new code but got stuck at building mujoco-py. 

I did the following steps (per various error messages while building mujoco-py):
(1) Downloaded Mujoco 2.0.0 from https://www.roboti.us/index.html to /home/$USER/.mujoco/mujoco200;
(2) Downloaded the license file mjkey.txt from https://www.roboti.us/license.html to /home/$USER/.mujoco;
(3) Added "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/$USER/.mujoco/mujoco200/bin" to .bashrc;
(4) Installed more libraries: sudo apt install libosmesa6-dev libgl1-mesa-glx libglfw3

However, I still see an error message:
Building wheel for mujoco-py (pyproject.toml) did not run successfully.
  │ exit code: 1
...
ImportError: /home/$USER/miniconda3/envs/diffuser/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib/x86_64-linux-gnu/libLLVM-13.so.1)

I'm still searching for the fixes towards this error. Any advice / guidance is much appreciated!

**Comment by RobotLearner2022** [comment]
Does the library work with a higher version of mujoco-py? I tried "pip install mujoco-py" and it went smoothly:
Collecting mujoco-py
  Downloading mujoco_py-2.1.2.14-py3-none-any.whl (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 4.0 MB/s eta 0:00:00
