### ISSUE TITLE
Why the visualization of kuka environment is totally different from what you report in the paper and website?

### ISSUE THREAD

**Issue by Liang-ZX** [jannerm/diffuser#25]
Hello. Excuse me. 

I run your codes in kuka branch, but the visualization in OpenGL is totally different from what you report in the paper and website. 

Besides, in some visualization scenarios, the kuka end-effect even does not contact the block but pick it up. I wonder whether there is any problem about the code implementation.

Thanks. Looking forward to your reply.

**Comment by jannerm** [comment]
Regarding visualization: the rendering that happens during training is done in pybullet's default OpenGL. We export the same state sequences to [Blender](https://www.blender.org/) to make the presentation-quality images and videos. The high-resolution Blender images are much slower to render, so it wouldn't make sense to produce them during the training process.

Regarding the end effector: could you tell us more about what you ran, what you expected to happen, and what happened instead? This would let us provide a more informed answer.

**Comment by Liang-ZX** [comment]
Thanks for your reply. 

And regarding the end effector: In some training cases, the visualization results in OpenGL show that the end effector does not attach a block but picks the block up. Just as the images in [img1](https://github.com/Liang-ZX/imagebed/blob/main/kuka-question/img1.png) and [img2](https://github.com/Liang-ZX/imagebed/blob/main/kuka-question/img2.png), I wonder whether there is any problem about the code implementation for this phenomenon or it's just a problem of visualization.

![image](https://user-images.githubusercontent.com/42173433/211129653-452a9bb0-e5ed-4870-a600-492bd2b393d4.png)

Besides, one more question: Is it normal for the following warnings about urdf model when I run the code?
```
b3Printf: iiwa_link_ee_kuka
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: No inertial data for link, using mass=1, localinertiadiagonal = 1,1,1, identity local inertial frame
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
```

Thank you again.

**Comment by yilundu** [comment]
Hi, 

There is an action in the environment which causes the end effector to attach to block -- which will cause the block to be lifted with the arm. In the setting where the end effector is not directly next to block, this will lead to wild movements of the block, which will cause task failure.

The above errors are normal -- the URDF doesn't define physics properties for everything.

**Comment by Liang-ZX** [comment]
Thanks for your reply.

For the end effector: In my understanding, the function `add_fixed_constraint` causes the end effector to attach to block. 

But it seems that there is no guarantee to make sure the end effector is directly next to block? Then how to solve this situation? Or just let it fail?

Thank you again.

```python
def add_fixed_constraint(body, robot, robot_link=BASE_LINK, max_force=None):
    body_link = BASE_LINK
    body_pose = get_pose(body)
    #body_pose = get_com_pose(body, link=body_link)
    #end_effector_pose = get_link_pose(robot, robot_link)
    end_effector_pose = get_com_pose(robot, robot_link)
    grasp_pose = multiply(invert(end_effector_pose), body_pose)
    point, quat = grasp_pose
    # TODO: can I do this when I'm not adjacent?
    # joint axis in local frame (ignored for JOINT_FIXED)
    constraint = p.createConstraint(robot, robot_link, body, body_link,  # Both seem to work
                                    p.JOINT_FIXED, jointAxis=unit_point(),
                                    parentFramePosition=point,
                                    childFramePosition=unit_point(),
                                    parentFrameOrientation=quat,
                                    childFrameOrientation=unit_quat(),
                                    physicsClientId=CLIENT)
    if max_force is not None:
        p.changeConstraint(constraint, maxForce=max_force, physicsClientId=CLIENT)
    return constraint
```

**Comment by yilundu** [comment]
Hi Liang,

In the current code, if the robot choses to attach the end effector to the block when its not close, it will cause the entire environment to fail. The way to solve this would be to add code to check the distance between the pose of the end-effector and the block, and if that distance is smaller than a threshold, create the constraint.
