### ISSUE TITLE
Unable to reproduce Kuka Conditional Sampling Results

### ISSUE THREAD

**Issue by joeybose** [jannerm/diffuser#26]
Hi,
Thanks for open sourcing your code for the Kuka environment. It seems there might be a version issue in the code and in the conditonal sampling script guided sampling is no longer defined in the Trainer class.

In particular, running the code leads to an error where this function is not defined.
https://github.com/jannerm/diffuser/blob/kuka/scripts/conditional_kuka_planning_eval.py#L154

**Comment by yilundu** [comment]
Hi,

It turns out the relative import path is incorrect -- can you try now?

**Comment by joeybose** [comment]
Cool, that worked!
Also, I think you're missing an import at the top of the file:
`import os.path as osp`
Once you have this the code runs properly.  Closing the issue now.
