### ISSUE TITLE
Clarification on implementation of warm-starting diffusion

### ISSUE THREAD

**Issue by dtch1997** [jannerm/diffuser#28]
Hi, 

Thanks very much for open-sourcing this great work . I have a minor question about implementation details: 

In Section 5.4 of the paper, it is mentioned that warm-starting the diffusion from a previous time-step's plan can reduce the number of diffusion steps necessary. In this case, how do you configure the diffusion process to use fewer timesteps? Do you simply use the last 100 values of the original alphas and betas, or do you initialize new alphas/betas for fewer timesteps, or something else? 

Thanks!

**Comment by jannerm** [comment]
We use the same $\alpha$ and $\beta$ schedule from the original $N$-step forward process, just initialize the denoising process at $x_n$ for $n < N$ instead of $x_N$, where $x_n$ is the previous plan shifted by one timestep (and noised as a function of $n$.)
