### ISSUE TITLE
Build docker stops with an error

### ISSUE THREAD

**Issue by xmlyqing00** [jannerm/diffuser#3]
Hi,

I tried to create a conda virtual environment but failed. So I turn to create a docker, but it fails at the same place, in creating the virtual environment.

```
#19 484.3   subprocess.CalledProcessError: Command '['/opt/conda/envs/diffuser/bin/python', 'dm_control/autowrap/autowrap.py', '--header_paths=/root/.mujoco/mujoco200_linux/include/mjdata.h /root/.mujoco/mujoco200_linux/include/mjmodel.h /root/.mujoco/mujoco200_linux/include/mjrender.h /root/.mujoco/mujoco200_linux/include/mjui.h /root/.mujoco/mujoco200_linux/include/mjvisualize.h /root/.mujoco/mujoco200_linux/include/mjxmacro.h /root/.mujoco/mujoco200_linux/include/mujoco.h', '--output_dir=/tmp/pip-install-alxuyfnp/dm-control_837352932d0a4468a1a9f22aec04744b/build/lib/dm_control/mujoco/wrapper/mjbindings']' returned non-zero exit status 1.                                                                        
#19 484.3   ----------------------------------------                                                                    
#19 484.3   ERROR: Failed building wheel for dm-control                                                                 
#19 484.3 ERROR: Could not build wheels for mujoco-py which use PEP 517 and cannot be installed directly 
```

I guess the problem is related to dm-control. Do you have any suggestion to fix it? Thanks.

**Comment by xmlyqing00** [comment]
Actually I figured it out. Just need to change the dependency from `mujoco-py=2.0.2.13` to `mujoco-py<2.2,>=2.1 # 2.0.2.13`. It can solve the most problems. There're some other typos like "diffusion" and "diffuser". I can create a pull request to fix them.

**Comment by jannerm** [comment]
Could you check if https://github.com/jannerm/diffuser/commit/067bd52d603b29687c11eabc088ec87c45b3e6f0 fixes it? I think the root problem might have come from a change in `dm-control` (possibly a branch name change), so I've updated the pinned `d4rl` version to point to the current head of `dm-control` with https://github.com/jannerm/d4rl/commit/13fc08c198d17ac627f528aedc70843e8f86bb71.

And good catch with the Dockerfile! I've fixed that in https://github.com/jannerm/diffuser/commit/e174300835153af6327bf4c88e7385155b5ec32a. Feel free to submit a PR for anything else you find.

**Comment by xmlyqing00** [comment]
Yes. It works perfectly. Thanks!!

I update some changes in README.  You can see the pull request for details.
