### ISSUE TITLE
Mismatch between paper and code when sampling?

### ISSUE THREAD

**Issue by joaoamcarvalho** [jannerm/diffuser#30]
Great work and thank you for sharing the code.

I have a question about a possible mismatch in guided sampling between the paper and the code.

In the paper, Algorithm 1: (1) you first compute the reverse transition, (2) afterwards add the gradient of the return, and (3) finally sample.

In the code it appears that operations (1) and (2) are switched, [here](https://github.com/jannerm/diffuser/blob/main/diffuser/sampling/functions.py#L29), is this intended?

Thanks!

**Comment by jannerm** [comment]
Nice catch! This was not intended, and was probably an unintentional change made during the pre-release refactor. My suspicion is that it should not affect the results, but because I don't have the GPUs to test that at the moment, I'll leave this issue open for the time being.

**Comment by joaoamcarvalho** [comment]
I also think it should not alter the results.
We found the main performance gains come from not adding noise to the last diffusion step and not scaling the gradient with the denoising variance.

**Comment by jannerm** [comment]
That is very good to know! Thanks for following up with the update.
