### ISSUE TITLE
About results in Table 2

### ISSUE THREAD

**Issue by Looomo** [jannerm/diffuser#31]
Hi, 
 One more question, just to make sure，the results in Table 2 are obtained by timing `score` with 100, is that right?

![image](https://user-images.githubusercontent.com/29702226/222393459-01c4f356-8d11-4aef-8632-6082b6098e3b.png)

![image](https://user-images.githubusercontent.com/29702226/222393629-5f8fef6d-9516-4d33-898b-9ebdb2810ec9.png)

**Comment by jannerm** [comment]
Yes, that is correct!

**Comment by jannerm** [comment]
Yes, that is correct.

You can also run [scripts/read_results.py](https://github.com/jannerm/diffuser/blob/main/scripts/read_results.py) to cross-reference the results with the numbers in the paper. The multiplication by 100 happens on [this line](https://github.com/jannerm/diffuser/blob/main/scripts/read_results.py#L59).
