### ISSUE TITLE
Can't run the code

### ISSUE THREAD

**Issue by xizaoqu** [jannerm/diffuser#33]
Hi, great work! However, I have a problem running it. I hope you can give me some suggestions.
When I ran the command `python scripts/plan_maze2d.py --config config.maze2d --dataset maze2d-large-v1`, it says I don't have module `tap`. So I install `tap==0.2` and `mc-bin-client==1.0.1`. But it seems just support Python 2, so there are many errors.

**Comment by xizaoqu** [comment]
I just modified the code and removed the requirement of `tap`.

**Comment by jannerm** [comment]
`tap` is short for `typed-argument-parser`, installed in [environment.yml:L16](https://github.com/jannerm/diffuser/blob/main/environment.yml#L16). I'd recommend checking out the [installation](https://github.com/jannerm/diffuser#installation) section of the README.

**Comment by xizaoqu** [comment]
> `tap` is short for `typed-argument-parser`, installed in [environment.yml:L16](https://github.com/jannerm/diffuser/blob/main/environment.yml#L16). I'd recommend checking out the [installation](https://github.com/jannerm/diffuser#installation) section of the README.

Thanks for your reply. I slacked off and build the env based on the old env... The problem is solved now.
