### ISSUE TITLE
 Inquiry About the Tool Used for 3D Plotting in Your Impressive Project

### ISSUE THREAD

**Issue by Waybaba** [jannerm/diffuser#37]
Firstly, I want to express my admiration for the outstanding work you've done on this project. It truly showcases the attention to detail and dedication put into it.

I am particularly intrigued by the 3D plot illustrating a robot arm stacking towers. It adds a visual dimension to the project that significantly aids in comprehension. I am interested in learning more about the tool or tools you used to create this visualization.

Could you kindly share information on the software, libraries, or methods employed to generate such a detailed 3D plot? Any pointers or references you could provide would be greatly appreciated, as they would greatly help me in furthering my own work in this domain.

Thank you in advance for your time and assistance!

**Comment by jannerm** [comment]
Thanks! I used [Blender](https://www.blender.org/), an open-source rendering engine.
