### ISSUE TITLE
Rendering problem with Maze2d environments

### ISSUE THREAD

**Issue by he-nantian** [jannerm/diffuser#42]
It is a wonderful work to reproduce! However, when I try Maze2d environments, sampling pictures in 'logs' directory are always in a flat view that I can't see the real situation of the maze, while other environments seem normal. How can I fix it?

**Comment by Super1ce** [comment]
Hi, did you achieve the results of the paper when running on maze2d? If so, how did you set it up? I raised an issue but he hasn’t replied yet.

**Comment by he-nantian** [comment]
> Hi, did you achieve the results of the paper when running on maze2d? If so, how did you set it up? I raised an issue but he hasn’t replied yet.

I have finished training and planning is on the way. I will show it to you once I have those results.

**Comment by jannerm** [comment]
Could you post an example of what the images look like, and what you expected instead?

**Comment by he-nantian** [comment]
> 

I have solved it and now it works normal. Thanks for your concern.

**Comment by he-nantian** [comment]
> Could you post an example of what the images look like, and what you expected instead?

I am trying to reproduce the results in table 1 but can only achieve normalized score of 1~2. Is it because scores are multiplied by 100 in table 1?

**Comment by jannerm** [comment]
Yes, the D4RL [normalization function](https://github.com/Farama-Foundation/D4RL/blob/71a9549f2091accff93eeff68f1f3ab2c0e0a288/d4rl/__init__.py#L58-L61) will map a random policy to 0 and the reference expert to 1. We [multiply by 100 here for the tables](https://github.com/jannerm/diffuser/blob/main/scripts/read_results.py#L59).

**Comment by jannerm** [comment]
Another way of verifying this is to look at the generated rollouts from the trained model. If they look good and have a score of 1~2, then that means the policy is close to (or in the case of `maze2d`, better than) the expert.

**Comment by he-nantian** [comment]
> Another way of verifying this is to look at the generated rollouts from the trained model. If they look good and have a score of 1~2, then that means the policy is close to (or in the case of `maze2d`, better than) the expert.

I got it. Thank you so much.
