### ISSUE TITLE
Dataset availability

### ISSUE THREAD

**Issue by a-nooj** [jannerm/diffuser#51]
Hi, where can I find the datasets for all the environments, esp. Maze2D?
Sorry if I missed this in the readme.

**Comment by jannerm** [comment]
They are from D4RL and will be downloaded automatically when running any of the scripts that use them (eg [here](https://github.com/jannerm/diffuser/blob/main/scripts/train.py#L36)).

**Comment by Haonote** [comment]
@jannerm Excuse me, does this mean that I don't need to download the dataset and run the code directly?
