### ISSUE TITLE
How did you generated datas for KUKA?

### ISSUE THREAD

**Issue by IlkwonHong** [jannerm/diffuser#52]
Did you manually created datasets of block stacking task?

**Comment by IlkwonHong** [comment]
Oh, I think there are some links in appendix...

**Comment by WAYKEN-TSE** [comment]
hi,I just face the same problem,the error like this:
"FileNotFoundError: [Errno 2] No such file or directory: 'logs/multiple_cube_kuka_convnew_real2_128'"
could you please tell me how can i get this data,hope for your reply
