### ISSUE TITLE
Conda environment cannot be created (wheel - mujoco-py problem)

### ISSUE THREAD

**Issue by staycoolish** [jannerm/diffuser#58]
Hello, when I try to build the conda environment, I get the following error:

```
Building wheel for mujoco-py (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [95 lines of output]
      running bdist_wheel
      running build
```

I tried lots of things, changed environment.yml file a lot, but nothing worked. Here is the latest environment.yml file (not sure if Cmake necessary):

```
name: diffuser
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- setuptools == 63.2.0
- wheel == 0.38.4
- pip == 22.2.2
- patchelf == 0.15.0.0
- Cmake
- pip:
    - -f https://download.pytorch.org/whl/torch_stable.html
    - numpy
    - gym==0.18.0
    - mujoco-py==2.0.2.13
    - matplotlib==3.3.4
    - torch==1.9.1+cu111
    - typed-argument-parser
    - git+https://github.com/Farama-Foundation/d4rl@f2a05c0d66722499bf8031b094d9af3aea7c372b#egg=d4rl
    - scikit-image==0.17.2
    - scikit-video==1.1.11
    - gitpython
    - einops
    - ffmpeg
    - ffprobe
    - pillow==7.2.0
    - tqdm
    - pandas
    - wandb
    - flax >= 0.3.5
    - jax <= 0.2.21
    - ray==2.0.0
    - crcmod # for fast gsutil rsync on large files
    - google-api-python-client
    - cryptography
    - git+https://github.com/JannerM/doodad.git@janner
    - gdown>=4.6.0
```

Note that, I successfully built the environment when I change the mujoco-py version to 2.0.2.8 , but when I try to run the planning example, I get an error; therefore installing another mujoco-py version seems useless. If someone has a working environment.yml version or any suggestions, it would be great. I have Ubuntu 20.4.6.

Also, I checked two other papers' implementations: Decision Diffuser and Diffusion Policy. Decision Diffuser has a similar environment.yml file (I modified a bit as well), and it gives the same error - wheel for mujoco-py:

```
name: decdiff
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- setuptools == 63.2.0
- wheel == 0.38.4
- pip
- patchelf
- Cmake
- pip:
    - -f https://download.pytorch.org/whl/torch_stable.html
    - numpy
    - gym==0.18.0
    - mujoco-py==2.0.2.13
    - matplotlib==3.3.4
    - torch==1.9.1+cu111
    - typed-argument-parser
    - git+https://github.com/rail-berkeley/d4rl@master#egg=d4rl
    - scikit-image==0.17.2
    - scikit-video==1.1.11
    - gitpython
    - einops
    - pillow==7.2.0
    - tqdm
    - pandas
    - wandb
    - flax >= 0.3.5
    - jax <= 0.2.21
    - ray==1.9.1
    - crcmod # for fast gsutil rsync on large files
    - ml_logger==0.8.69 
    - jaynes==0.8.11 
    - params_proto==2.9.6
```
Diffusion Policy uses rather different packages, here is its environment.yml file, and it works actually (I didn't modify it):

```
name: robodiff
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pip=22.2.2
  - cudatoolkit=11.6
  - pytorch=1.12.1
  - torchvision=0.13.1
  - pytorch3d=0.7.0
  - numpy=1.23.3
  - numba==0.56.4
  - scipy==1.9.1
  - py-opencv=4.6.0
  - cffi=1.15.1
  - ipykernel=6.16
  - matplotlib=3.6.1
  - zarr=2.12.0
  - numcodecs=0.10.2
  - h5py=3.7.0
  - hydra-core=1.2.0
  - einops=0.4.1
  - tqdm=4.64.1
  - dill=0.3.5.1
  - scikit-video=1.1.11
  - scikit-image=0.19.3
  - gym=0.21.0
  - pymunk=6.2.1
  - wandb=0.13.3
  - threadpoolctl=3.1.0
  - shapely=1.8.4
  - cython=0.29.32
  - imageio=2.22.0
  - imageio-ffmpeg=0.4.7
  - termcolor=2.0.1
  - tensorboard=2.10.1
  - tensorboardx=2.5.1
  - psutil=5.9.2
  - click=8.0.4
  - boto3=1.24.96
  - accelerate=0.13.2
  - datasets=2.6.1
  - diffusers=0.11.1
  - av=10.0.0
  - cmake=3.24.3
  # trick to avoid cpu affinity issue described in https://github.com/pytorch/pytorch/issues/99625
  - llvm-openmp=14
  # trick to force reinstall imagecodecs via pip
  - imagecodecs==2022.8.8
  - pip:
    - ray[default,tune]==2.2.0
    # requires mujoco py dependencies libosmesa6-dev libgl1-mesa-glx libglfw3 patchelf
    - free-mujoco-py==2.1.6
    - pygame==2.1.2
    - pybullet-svl==3.1.6.4
    - robosuite @ https://github.com/cheng-chi/robosuite/archive/277ab9588ad7a4f4b55cf75508b44aa67ec171f0.tar.gz
    - robomimic==0.2.0
    - pytorchvideo==0.1.5
    # pip package required for jpeg-xl
    - imagecodecs==2022.9.26
    - r3m @ https://github.com/facebookresearch/r3m/archive/b2334e726887fa0206962d7984c69c5fb09cceab.tar.gz
    - dm-control==1.0.9
```
Perhaps using free-mujoco-py instead of mujoco-py could be useful?

Thanks in advance,

**Comment by Chenrf1121** [comment]
When I install `mujoco-py==2.0.2.8`, I can build the environment, run `python scripts/plan_guided.py --dataset halfcheetah-medium-expert-v2 --logbase logs/pretrained`,  error is `Exception check on 'c_error_callback' will always require the GIL to be acquired.
Possible solutions:
        1. Declare 'c_error_callback' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
        2. Use an 'int' return type on 'c_error_callback' to allow an error code to be returned.

Error compiling Cython file:
------------------------------------------------------------
...
    See c_warning_callback, which is the C wrapper to the user defined function
    '''
    global py_warning_callback
    global mju_user_warning
    py_warning_callback = warn
    mju_user_warning = c_warning_callback
                       ^
------------------------------------------------------------`. If `mujoco-py==2.0.2.13`, I cannot build the environment, error is `Building wheel for mujoco-py (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [95 lines of output]
      running bdist_wheel
      running build
      performance hint: mujoco_py/cymj.pyx:67:5: Exception check on 'c_warning_callback' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare 'c_warning_callback' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on 'c_warning_callback' to allow an error code to be returned.
      performance hint: mujoco_py/cymj.pyx:104:5: Exception check on 'c_error_callback' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare 'c_error_callback' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on 'c_error_callback' to allow an error code to be returned.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          See c_warning_callback, which is the C wrapper to the user defined function
          '''
          global py_warning_callback
          global mju_user_warning
          py_warning_callback = warn
          mju_user_warning = c_warning_callback
                             ^
      ------------------------------------------------------------
      
      mujoco_py/cymj.pyx:92:23: Cannot assign type 'void (const char *) except * nogil' to 'void (*)(const char *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to the type of 'c_warning_callback'.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          See c_warning_callback, which is the C wrapper to the user defined function
          '''
          global py_error_callback
          global mju_user_error
          py_error_callback = err_callback
          mju_user_error = c_error_callback
                           ^
      ------------------------------------------------------------
      
      mujoco_py/cymj.pyx:127:21: Cannot assign type 'void (const char *) except * nogil' to 'void (*)(const char *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to the type of 'c_error_callback'.
      Removing old mujoco_py cext /tmp/pip-install-qcc9q_sg/mujoco-py_94935ba32fc043aeb9a8b7c157305dbd/mujoco_py/generated/cymj_2.0.2.13_38_linuxcpuextensionbuilder_38.so
      Compiling /tmp/pip-install-qcc9q_sg/mujoco-py_94935ba32fc043aeb9a8b7c157305dbd/mujoco_py/cymj.pyx because it changed.
      [1/1] Cythonizing /tmp/pip-install-qcc9q_sg/mujoco-py_94935ba32fc043aeb9a8b7c157305dbd/mujoco_py/cymj.pyx`

**Comment by NishanthARao** [comment]
Here's what worked for me (Ubuntu 22.04):

1. Downgraded Python 3.12 to Python 3.8 by using `conda install python=3.8`
2. Install specific versions of setuptools and wheel: `pip3 install setuptools==65.5.0 "wheel<0.40.0"`
3. Install cython<3 using `pip3 install cython<3`
4. Replace `mujoco-py==2.0.2.13` with `mujoco-py==2.0.2.5`

My `environment.yml` file looks like this:

```bash
name: diffuser
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- pip
- patchelf
- pip:
    - -f https://download.pytorch.org/whl/torch_stable.html
    - setuptools==65.5.0
    - wheel<0.40.0
    - mujoco-py==2.0.2.5
    - numpy
    - gym==0.18.0
    - matplotlib==3.3.4
    - torch==1.9.1+cu111
    - typed-argument-parser
    - git+https://github.com/Farama-Foundation/d4rl@f2a05c0d66722499bf8031b094d9af3aea7c372b#egg=d4rl
    - scikit-image==0.17.2
    - scikit-video==1.1.11
    - gitpython
    - einops
    - ffmpeg
    - ffprobe
    - pillow
    - tqdm
    - pandas
    - wandb
    - flax >= 0.3.5
    - jax <= 0.2.21
    - ray==2.0.0
    - crcmod # for fast gsutil rsync on large files
    - google-api-python-client
    - cryptography
    - git+https://github.com/JannerM/doodad.git@janner
    - gdown>=4.6.0
```

Other minor fixes I had to make:

1. Convert `np.int` to `np.int64` in file `buffer.py`  (`diffuser/datasets/`)
2. Fix errors pertaining to LibGLEW.so and LibGL.so - This link helped a lot!

https://github.com/yuqingd/sim2real2sim_rad/blob/master/README.md#debugging-common-installation-errors

**Comment by ShawnKing98** [comment]
> Here's what worked for me (Ubuntu 22.04):
> 
> 1. Downgraded Python 3.12 to Python 3.8 by using `conda install python=3.8`
> 2. Install specific versions of setuptools and wheel: `pip3 install setuptools==65.5.0 "wheel<0.40.0"`
> 3. Install cython<3 using `pip3 install cython<3`
> 4. Replace `mujoco-py==2.0.2.13` with `mujoco-py==2.0.2.5`
> 
> My `environment.yml` file looks like this:
> 
> ```shell
> name: diffuser
> channels:
> - defaults
> - conda-forge
> dependencies:
> - python=3.8
> - pip
> - patchelf
> - pip:
>     - -f https://download.pytorch.org/whl/torch_stable.html
>     - setuptools==65.5.0
>     - wheel<0.40.0
>     - mujoco-py==2.0.2.5
>     - numpy
>     - gym==0.18.0
>     - matplotlib==3.3.4
>     - torch==1.9.1+cu111
>     - typed-argument-parser
>     - git+https://github.com/Farama-Foundation/d4rl@f2a05c0d66722499bf8031b094d9af3aea7c372b#egg=d4rl
>     - scikit-image==0.17.2
>     - scikit-video==1.1.11
>     - gitpython
>     - einops
>     - ffmpeg
>     - ffprobe
>     - pillow
>     - tqdm
>     - pandas
>     - wandb
>     - flax >= 0.3.5
>     - jax <= 0.2.21
>     - ray==2.0.0
>     - crcmod # for fast gsutil rsync on large files
>     - google-api-python-client
>     - cryptography
>     - git+https://github.com/JannerM/doodad.git@janner
>     - gdown>=4.6.0
> ```
> 
> Other minor fixes I had to make:
> 
> 1. Convert `np.int` to `np.int64` in file `buffer.py`  (`diffuser/datasets/`)
> 2. Fix errors pertaining to LibGLEW.so and LibGL.so - This link helped a lot!
> 
> https://github.com/yuqingd/sim2real2sim_rad/blob/master/README.md#debugging-common-installation-errors

This works for me, thanks!

**Comment by staycoolish** [comment]
> Here's what worked for me (Ubuntu 22.04):
> 
>     1. Downgraded Python 3.12 to Python 3.8 by using `conda install python=3.8`
> 
>     2. Install specific versions of setuptools and wheel: `pip3 install setuptools==65.5.0 "wheel<0.40.0"`
> 
>     3. Install cython<3 using `pip3 install cython<3`
> 
>     4. Replace `mujoco-py==2.0.2.13` with `mujoco-py==2.0.2.5`
> 
> 
> My `environment.yml` file looks like this:
> 
> ```shell
> name: diffuser
> channels:
> - defaults
> - conda-forge
> dependencies:
> - python=3.8
> - pip
> - patchelf
> - pip:
>     - -f https://download.pytorch.org/whl/torch_stable.html
>     - setuptools==65.5.0
>     - wheel<0.40.0
>     - mujoco-py==2.0.2.5
>     - numpy
>     - gym==0.18.0
>     - matplotlib==3.3.4
>     - torch==1.9.1+cu111
>     - typed-argument-parser
>     - git+https://github.com/Farama-Foundation/d4rl@f2a05c0d66722499bf8031b094d9af3aea7c372b#egg=d4rl
>     - scikit-image==0.17.2
>     - scikit-video==1.1.11
>     - gitpython
>     - einops
>     - ffmpeg
>     - ffprobe
>     - pillow
>     - tqdm
>     - pandas
>     - wandb
>     - flax >= 0.3.5
>     - jax <= 0.2.21
>     - ray==2.0.0
>     - crcmod # for fast gsutil rsync on large files
>     - google-api-python-client
>     - cryptography
>     - git+https://github.com/JannerM/doodad.git@janner
>     - gdown>=4.6.0
> ```
> 
> Other minor fixes I had to make:
> 
>     1. Convert `np.int` to `np.int64` in file `buffer.py`  (`diffuser/datasets/`)
> 
>     2. Fix errors pertaining to LibGLEW.so and LibGL.so - This link helped a lot!
> 
> 
> https://github.com/yuqingd/sim2real2sim_rad/blob/master/README.md#debugging-common-installation-errors



> Here's what worked for me (Ubuntu 22.04):
> 
>     1. Downgraded Python 3.12 to Python 3.8 by using `conda install python=3.8`
> 
>     2. Install specific versions of setuptools and wheel: `pip3 install setuptools==65.5.0 "wheel<0.40.0"`
> 
>     3. Install cython<3 using `pip3 install cython<3`
> 
>     4. Replace `mujoco-py==2.0.2.13` with `mujoco-py==2.0.2.5`
> 
> 
> My `environment.yml` file looks like this:
> 
> ```shell
> name: diffuser
> channels:
> - defaults
> - conda-forge
> dependencies:
> - python=3.8
> - pip
> - patchelf
> - pip:
>     - -f https://download.pytorch.org/whl/torch_stable.html
>     - setuptools==65.5.0
>     - wheel<0.40.0
>     - mujoco-py==2.0.2.5
>     - numpy
>     - gym==0.18.0
>     - matplotlib==3.3.4
>     - torch==1.9.1+cu111
>     - typed-argument-parser
>     - git+https://github.com/Farama-Foundation/d4rl@f2a05c0d66722499bf8031b094d9af3aea7c372b#egg=d4rl
>     - scikit-image==0.17.2
>     - scikit-video==1.1.11
>     - gitpython
>     - einops
>     - ffmpeg
>     - ffprobe
>     - pillow
>     - tqdm
>     - pandas
>     - wandb
>     - flax >= 0.3.5
>     - jax <= 0.2.21
>     - ray==2.0.0
>     - crcmod # for fast gsutil rsync on large files
>     - google-api-python-client
>     - cryptography
>     - git+https://github.com/JannerM/doodad.git@janner
>     - gdown>=4.6.0
> ```
> 
> Other minor fixes I had to make:
> 
>     1. Convert `np.int` to `np.int64` in file `buffer.py`  (`diffuser/datasets/`)
> 
>     2. Fix errors pertaining to LibGLEW.so and LibGL.so - This link helped a lot!
> 
> 
> https://github.com/yuqingd/sim2real2sim_rad/blob/master/README.md#debugging-common-installation-errors

----------------------------------------------------------------------------------------------------------------------------------------------------------------

Thank you @NishanthARao ! Although this didn't work on my computer (perhaps due to Ubuntu 20.04, I couldn't build the environment), I tried the only environment version I could build, using mujoco-py 2.0.2.5 this time (I used 2.0.2.8 before, environment was built but then I got many errors), and it worked: 

Here is the environment.yml file:

```
name: diffuser
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- setuptools == 63.2.0
- wheel == 0.38.4
- pip == 22.2.2
- patchelf == 0.15.0.0
- Cmake
- cython == 0.29.36
- pip:
    - -f https://download.pytorch.org/whl/torch_stable.html
    - numpy
    - gym==0.18.0
    - mujoco-py==2.0.2.5
    - matplotlib==3.3.4
    - torch==1.9.1+cu111
    - typed-argument-parser
    - git+https://github.com/Farama-Foundation/d4rl@f2a05c0d66722499bf8031b094d9af3aea7c372b#egg=d4rl
    - scikit-image==0.17.2
    - scikit-video==1.1.11
    - gitpython
    - einops
    - ffmpeg
    - ffprobe
    - pillow==7.2.0
    - tqdm
    - pandas
    - wandb
    - flax >= 0.3.5
    - jax <= 0.2.21
    - ray==2.0.0
    - crcmod # for fast gsutil rsync on large files
    - google-api-python-client
    - cryptography
    - git+https://github.com/JannerM/doodad.git@janner
    - gdown>=4.6.0
```

I only had to change `np.int` to `np.int64` in file buffer.py (diffuser/datasets/), and that was it!
