### ISSUE TITLE
A question regarding two details mentioned in the paper.

### ISSUE THREAD

**Issue by AIasd** [jannerm/diffuser#7]
Thank you for publicizing your code! I have a question regarding two details mentioned in the part below:

![image](https://user-images.githubusercontent.com/12670254/172676179-e52dcaa5-5c84-43da-ac89-3332698ceea5.png)

In the paper, it mentions "the training of a cumulative reward classifier" and "use the first action in the environment".

It seems these are not present in the current demo code for the hopper experiment. Am I understanding correctly? 

Thank you!

**Comment by yilundu** [comment]
Hi,

Yes, code for sampling based off the gradient of the value function is not available in the code right now -- we will update the repo by the end of June with the full code.
