### ISSUE TITLE
A minor issue when training models with maze2d dataset

### ISSUE THREAD

**Issue by zanghyu** [jannerm/diffuser#8]
Hi,

Thanks for sharing the nice code! There was a minor issue when I trained the model with the script `python scripts/train.py --dataset maze2d-umaze-v1 --horizon 512 --n_diffusion_steps 200`:

```
File ".../diffuser/datasets/buffer.py", line 75, in add_path
    self._dict[key][self._count, :path_length] = array
IndexError: index 10000 is out of bounds for axis 0 with size 10000
```

and I believe the episode number of the maze2d dataset is more than 10000, which caused this error. So I set `max_n_episodes=20000` at the line: https://github.com/jannerm/diffuser/blob/main/diffuser/datasets/sequence.py#L18. And it really fixed this issue.  Maybe you can update the corresponding code if I'm correct?

BTW, looking forward to seeing your testing/evaluating code :)

**Comment by yilundu** [comment]
Hi the maze2d code should be released now -- do you still have issues?

**Comment by zanghyu** [comment]
Thanks for the reply! But it seems the error still occurs...

**Comment by jannerm** [comment]
Thanks for reporting. Could you check that you're on the `maze2d` branch and using the default maze2d config?

```
git checkout maze2d
python scripts/train.py --config config.maze2d --dataset maze2d-large-v1
```

If that doesn't solve it, could you send the full stack trace?

**Comment by zanghyu** [comment]
Here's the stack trace:

```
Traceback (most recent call last):
  File "scripts/train.py", line 36, in <module>
    dataset = dataset_config()
  File "/data/hyzang/project/rl/representation/diffuser-main/maze2d/diffuser-maze2d/diffuser/utils/config.py", line 65, in __call__
    instance = self._class(*args, **kwargs, **self._dict)
  File "/data/hyzang/project/rl/representation/diffuser-main/maze2d/diffuser-maze2d/diffuser/datasets/sequence.py", line 28, in __init__
    fields.add_path(episode)
  File "/data/hyzang/project/rl/representation/diffuser-main/maze2d/diffuser-maze2d/diffuser/datasets/buffer.py", line 75, in add_path
    self._dict[key][self._count, :path_length] = array
IndexError: index 10000 is out of bounds for axis 0 with size 10000
```

The default setting of the `max_n_episodes` being small could still be the issue?

**Comment by jannerm** [comment]
Could you include everything printed up until that point by the script? I think you're right that the `max_n_episodes` is what's causing the error locally, but I'm trying to figure out why you're getting the error when I don't, and looking at the printed configs might help me figure that out.

**Comment by zanghyu** [comment]
Sorry for the late reply, I have re-run the code today, and found it works! Thanks very much!
