### ISSUE TITLE
Condition DDPM

### ISSUE THREAD

**Issue by kailaisun** [jannerm/diffuser#9]
It seems that condition was not used in DDPM, in models.temporal.py. Function "apply_conditioning" only replaces the initial state.

**Comment by yilundu** [comment]
Yes, currently state conditioning in the model corresponds to setting a state in the trajectory to a particular value (there is no conditioning).

**Comment by jannerm** [comment]
Yes, in guided sampling for return maximization, [`apply_conditioning`](https://github.com/jannerm/diffuser/blob/f54f9d4dfaca798c350a1abdd242b7adc1078fa8/diffuser/models/helpers.py#L142-L145) only serves to replace the [current state](https://github.com/jannerm/diffuser/blob/main/scripts/plan_guided.py#L88), with the rest of the conditioning coming from the value function.

In the Maze2D goal-conditioned RL experiments, the conditions contain [both a current and a goal state](https://github.com/jannerm/diffuser/blob/maze2d/diffuser/datasets/sequence.py#L92-L99).
